### ISSUE TITLE
Music freezes 

### ISSUE THREAD

**Issue by Zayon** [smithdtyler/prettygoodmusicplayer#71] opened 2015-01-19 14:04 UTC
I just installed your app from F-Droid and the music stop for just a sec sometimes. I tried unistall / reinstall, it seemed to work at first but I still got  some freezes.

I use a Nexus 5 with SlimKat. VLC has no problem.

**Comment by smithdtyler** [comment] 2015-01-19 14:12
What file encoding are you using?

**Comment by Zayon** [comment] 2015-01-19 14:15
I only tested with mp3 files

**Comment by smithdtyler** [comment] 2015-01-19 14:24
I had another user with this issue about a month ago. He was using
CyanogenMod. I wasn't able to replicate the issue since CyanogenMod wasn't
supported on my phones.

My player just uses the built-in MediaPlayer API, so unfortunately I don't
know if there's much I can do (I've been unable to replicate the problem
using Stock android 4.2 or 4.4). I will leave this issue open and will
update it if I find any clues as to a potential fix.

Thanks for informing me of the issue.

**Comment by smithdtyler** [comment] 2015-01-24 04:01
Are you using Bluetooth headphones or conventional headphones?

**Comment by Zayon** [comment] 2015-02-09 12:41
Conventional headphones.
Sorry for late response

**Comment by Zayon** [comment] 2015-04-28 21:01
Gave it a try today with speakers, same problem.
Just wanted to let you know.

**Comment by smithdtyler** [comment] 2015-08-23 14:58
For a long time I had not seen this problem, but I encountered it a couple of days ago. I have no idea what might be causing it, but at least I'm able to replicate it with my current phone.

**Comment by rdelro** [comment] 2015-08-26 03:27
I can also confirm this problem on stock android 4.4.2 downloaded from the Play store! Using version 3.2.12 PGMP. it works fine on CM10 , android 4.1/4.x.y using an older version in F-Droid. Sorry if this isn't helpful. Just wanted to share that this is still occurring. Strange how the older version works fine?

**Comment by smithdtyler** [comment] 2015-08-26 11:45
I've seen behavior too! I don't know what's going on, but I will try to
figure it out. Thanks for the info.

To clarify, was it an older pgmp that worked, or an older Android?

**Comment by rdelro** [comment] 2015-08-26 18:48
Correct. The older version of PGMP(v3.2.12) worked fine on my older device(LG p500 series) android(v4.1?) device running a a custom version of CM10. Hope this information was helpful!

**Comment by smithdtyler** [comment] 2015-08-28 10:47
The only time I've seen this behavior is on my Android 5.0.1 phone. I never experienced it on my 4.x device. I'm trying to replicate it now (on 5.0.1), but I'm not having much luck...

**Comment by smithdtyler** [comment] 2015-08-28 10:57
The only time I've seen this issue is while the screen is off. Is that similar to what you've seen? I'm wondering if newer versions of Android don't go to sleep as gracefully as the older versions.

**Comment by Zayon** [comment] 2015-08-28 11:41
@smithdtyler I juste made the test, no problem as long as the sreen is on.

Maybe the freeze comes from the phone going in deep sleep ?

**Comment by smithdtyler** [comment] 2015-08-28 11:58
I'm going to try adding a WakeLock while music is playing. This will let the display turn off, but will keep the CPU on.

**Comment by smithdtyler** [comment] 2015-08-28 13:53
I just uploaded version 3.2.14. I *think* it will fix this problem. Once it's available (could take up to 24 hours) please give it a try! Thanks!

**Comment by rdelro** [comment] 2015-08-28 19:06
Hmm yeah not that I think about it, this issue only occurred when my screen was off. I use PGMP Launcher as my main driver on my old LG phone just because it has no other use. So turning it into a hack-iPod seemed to be the most useful idea. So having the screen on isnt something I need considering the battery life on it is horrid haha! I'll give the new version a try tomorrow just to give it time to update.

**Comment by smithdtyler** [comment] 2015-08-28 20:30
The screen won't be on, a wake lock can just keep the cpu awake so music
keeps playing.

On Aug 28, 2015 2:06 PM, "rom" <notifications@github.com> wrote:
>
> Hmm yeah not that I think about it, this issue only occurred when my
screen was off. I use PGMP Launcher as my main driver on my old LG phone
just because it has no other use. So turning it into a hack-iPod seemed to
be the most useful idea. So having the screen on isnt something I need
considering the battery life on it is horrid haha! I'll give the new
version a try tomorrow just to give it time to update.

**Comment by smithdtyler** [comment] 2015-08-31 13:35
I just encountered this issue again after installing the update that added a wakelock. Not sure what's causing the problem...

**Comment by rdelro** [comment] 2015-08-31 22:25
I was going to say perhaps it isnt your player, it's the devices' hardware? My phones suck and my tablet's OS does not compensate it's hardware at all. I cannot run any modern app for longer than just under 60sec at a time. Sucks because every web browser takes lots of time to load and by the time whatever on my screen is rendered (normally page banner) it crashes and I gotta start all over again. So regards to your music player, I tested a few others and not only did they kill my phone's performance but they have crazy perms I don't approve of. (Why does a music player need access to your camera and mic? eh..) PGMP by far is the easiest on resources and its simple. It's really not a big deal to me personally if it crashes every now and again just cause of screen-lock. I'll keep my screen on and just turn the brightness to 0 and enjoy music. Good luck!

**Comment by snelltheta** [comment] 2015-09-08 07:29
I can confirm this is happening in Lollipop on Nexus 7 and LG G3 only when screen is off. Music will resume after a (yet undetermined, but long) while. Problems occurred with MP3 format; no other formats tested.

**Comment by smithdtyler** [comment] 2015-09-08 12:07
Thank you for the help. I'm continuing to test the app to try to figure out what's going on, I really apologize for this problem - nobody wants a music player that doesn't play consistently. 

Any ideas as to what might be wrong would be greatly appreciated. I added a Wake Lock in v3.2.14, but that doesn't seem to have completely addressed the problem.

**Comment by smithdtyler** [comment] 2015-10-12 22:10
I've been able to replicate this issue occasionally. I haven't found any
consistent correlation between file type and error behavior, but I'll keep
searching.

To be honest there's not a whole lot I can do, the file is just passed
directly to Android's media player.

**Comment by snelltheta** [comment] 2015-10-13 03:01
Is there anything considering process priority that hasn't been 
attempted to fix this bug?

**Comment by smithdtyler** [comment] 2015-10-13 08:57
I've never had this problem playing over Bluetooth, perhaps that causes it
to run with a different priority?

**Comment by smithdtyler** [comment] 2015-10-13 12:19
Asked on [Stackoverflow](https://stackoverflow.com/questions/33100278/android-mediaplayer-playback-stutters-over-wired-headphones-not-over-bluetooth).

**Comment by smithdtyler** [comment] 2015-10-14 15:36
Could it be a problem with the target Android version? It's targeting 19 right now - does the runtime behavior change for different target SDKs?

**Comment by smithdtyler** [comment] 2015-10-14 15:38
Found this question - looked like a possible performance issue:

https://stackoverflow.com/questions/32295029/does-the-compile-sdk-affect-values-returned-by-android-functions

*It's important to note that devices with an API higher than the targetSdkVersion will attempt emulate down to the lower target API level:*

**Comment by adrian-bl** [comment] 2015-10-14 20:40
> I've never had this problem playing over Bluetooth, perhaps that causes it to run with a different 
> priority?

The MediaPlayer inherits the thread priority of the thread which calls start() on it. (This is weird and undocumented, but android works like this). But this shouldn't cause any issues unless you call mp.start() in an handler thread with PRIORITY_LOWEST (PRIORITY_DEFAULT should be good enough for music playback)

I'd rather suspect a scheduler issue on the phone (i've seen something similar on my old HTC One X):

Let's say that playing an MP3 file requires 270Mhz, so the kernel may keep the CPU clocked at 300MHz. This may work well in most cases, but sometimes another process gets some CPU time and the kernel runs out of jiffies.

If you do exactly the same via BT, then the kernel may clock the CPU at an higher speed because the SBC encoder (BT audio coded) also requires CPU, so your processor may run at eg. 400Mhz (or whatever the next scaling step of the CPU is) which may be fast enough to even-out small hickups.

**Comment by smithdtyler** [comment] 2015-10-15 02:40
That makes sense, but is there any way it can be addressed? Adding a CPU wakelock didn't seem to have any effect on the problem.

**Comment by smithdtyler** [comment] 2015-10-15 03:29
I'm trying the MediaPlayer.setWakeLock() method to see if it has any effect.

**Comment by smithdtyler** [comment] 2015-10-15 13:29
It took about an hour, but I still got a random pause after applying the mediaplayer wakelock change.

**Comment by smithdtyler** [comment] 2015-10-18 12:47
The frequency of the pauses seems to accelerate over time. At first it's once per hour, but then the time between pauses decreases by about half each time, until it's pausing almost every minute.

**Comment by smithdtyler** [comment] 2015-10-18 13:15
Perhaps I'm not releasing the media player resources like I should? Do I need to destroy it and create a new one periodically?

**Comment by adrian-bl** [comment] 2015-10-18 13:25
No - you should in fact keep it around as long as possible.

Setting the wakeLock won't do anything about this: Having an active wake-lock just tells android to not go into deep-sleep.
Do you have root on the affected phone? if yes, then i'd try to set the min-frequency to something high (~800mhz) to rule out frequency scaling issues.
And: Do you play the music from the internal storage or an sd-card? It could also be related to IO. (We have a 'preread playing song' option in Vanilla music to work around similar issues)

**Comment by smithdtyler** [comment] 2015-10-18 14:46
*And: Do you play the music from the internal storage or an sd-card? It could also be related to IO. (We have a 'preread playing song' option in Vanilla music to work around similar issues)*

Yes, what does 'preread' mean?

**Comment by adrian-bl** [comment] 2015-10-18 16:12
> Yes, what does 'preread' mean?

We use a separated thread to read-ahead the currently playing file:

-> The thread reads the file with about 256kb/s, so it will read the file faster than mediaserver does
-> This gives the file a very good chance to stay in the page/disk cache
-> ..and this minimizes the chance for 'drop outs' due to funky sd-cards or other IO-pauses.

The code is located here: https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/ReadaheadThread.java
The code does not depend on any parts of vanilla music: if you would like to give it a try, just drop it into your project and do something like:
```
onCreate {
 ...
 mReadaheadThread = new ReadaheadThread.java
 ...
}
...
mMediaPlayer.setDataSource(path);
mReadaheadThread.setDataSource(path);
...
```

**Comment by smithdtyler** [comment] 2015-10-25 07:45
I have yet to reproduce the problem after adopting your recommendation! I'm going to test a bit more, but I think this problem is resolved. Thanks a ton!!

**Comment by smithdtyler** [comment] 2015-10-26 23:31
I have not been able to replicate the problem!  I'm going to close this issue. Please let me know if you encounter this problem again.

**Closed by smithdtyler** 2015-10-26 23:31 UTC
Labels: bug
