### ISSUE TITLE
FLAC support?

### ISSUE THREAD

**Issue by hatul-madan** [smithdtyler/prettygoodmusicplayer#110] opened 2016-02-25 14:26 UTC
Using version 3.3.0 i see directories containing .flac files as empty.  Other players play flacs with no problems. Looks similar to issue#95, but that one seemed format-independent. Tested on two different devices.

**Comment by smithdtyler** [comment] 2016-02-25 15:36
Huh... This has worked in the past, perhaps we've had a regression... I'll
check it out.

**Comment by undu** [comment] 2016-02-26 12:11
This is probably my fault: https://github.com/smithdtyler/prettygoodmusicplayer/pull/106
I'll see if I missed some flac media type. Otherwise can just merge the generated extension list with the static we had before, not ideal but it'll work.

**Comment by undu** [comment] 2016-02-26 12:49
I missed the audio/x-flac media type, but I don't know if that will fix it.

Here's an apk with the fix: https://github.com/undu/prettygoodmusicplayer/releases/download/3.3.0a/prettygoodmusicplayer-debug.apk

You'll have to delete the existing app to be able to install this one.

Check back if it works, otherwise we can apply a fix that merges the two extension lists.

**Comment by hatul-madan** [comment] 2016-02-26 15:35
undu, thank you for your help!
I tried your apk, but flacs are still invisible.

**Comment by undu** [comment] 2016-02-26 16:18
I've uploaded another binary to the same direction, let me know if it fixes the issue.

**Comment by hatul-madan** [comment] 2016-02-26 18:41
Tried it. No, unfortunately it doesn't.

**Comment by undu** [comment] 2016-02-26 18:51
Have you tried putting mp3 files to the same directory? This isn't a regression caused by my patch, I feel the issue you're having is due to https://github.com/smithdtyler/prettygoodmusicplayer/issues/104

**Comment by hatul-madan** [comment] 2016-02-26 19:31
I tried to put mp3 in the directory that contained flac files only. Initially in PGMP I saw it as empty, after mp3 addition I was able to see the added mp3 file in this folder, but nothing more. 
It's not #104, the folder now is "music/flac/album", and #104 manifests itself in mixing tracks from different albums.

**Comment by undu** [comment] 2016-02-26 19:51
Let's try one more time: https://github.com/undu/prettygoodmusicplayer/releases/download/3.3.0b/prettygoodmusicplayer-debug.apk

**Comment by hatul-madan** [comment] 2016-02-26 20:15
Still the same thing, sadly.

**Comment by undu** [comment] 2016-02-26 20:32
I'm sorry, for some reason the last change didn't go through, can you re-download and try again?

**Comment by hatul-madan** [comment] 2016-02-26 20:39
Tried again - no difference yet.

**Comment by undu** [comment] 2016-02-26 20:43
Have you tried the previous stable version?

https://f-droid.org/repo/com.smithdtyler.prettygoodmusicplayer_67.apk

**Comment by smithdtyler** [comment] 2016-02-26 20:51
Can you post the folder structure you have? A sample file would be good too.

**Comment by hatul-madan** [comment] 2016-02-26 22:30
> Have you tried the previous stable version?

Tried: this one worked.

>Can you post the folder structure you have?

It's large, but can be seen here: http://pastebin.com/HjvYwdZ7

>A sample file would be good too.

A sample flac file? For example, this one was invisible as any other: 
http://www.lindberg.no/hires/test/2L-111_15_stereo-44k-16b.flac

**Comment by smithdtyler** [comment] 2016-02-27 04:52
Sharing my debugging notes:

Utils.decodableMediaTypes is resolving to

![decodablemediatypes](https://cloud.githubusercontent.com/assets/8142684/13370847/0934e312-dcdb-11e5-9a33-1c9812c3ed33.png)

MediaTypeUtils.extensionToMimeTypeMap resolves to

![extensiontomimetypemap](https://cloud.githubusercontent.com/assets/8142684/13370859/5ffcdb82-dcdb-11e5-865a-6fba9b17f86d.png)

Looks like we're claiming it's not supported because the media type for flac doesn't exactly match the MimeType.

**Comment by smithdtyler** [comment] 2016-02-27 04:57
When I originally added the file type filter, it was mostly to avoid showing the user files that were in the folder by accident, or were added by some OS level nonsense (like OS X's .DS_Store files). The player will fail gracefully if it tries to play a file and fails.  Unless I'm convinced otherwise, I'm going to relax the restriction so that if the extension shows up in MediaTypeUtils, we call it good.

**Comment by smithdtyler** [comment] 2016-02-27 05:17
That test file is working for me with version 3.3.1 (just tagged). I've not tested it with your folder structure yet. Please let me know if this solves the issue.

[3.3.1 APK](https://drive.google.com/file/d/0BxNDTlnbuMgUY3lpYmQtNWF1Ym8/view?usp=sharing)

**Comment by hatul-madan** [comment] 2016-02-27 06:07
Tried it, now it works! All flacs are visible and playable. Thank you!

**Comment by smithdtyler** [comment] 2016-03-11 05:22
This fix is included in 3.3.2

**Closed by smithdtyler** 2016-03-11 05:22 UTC
