### ISSUE TITLE
Subfolders are not displayed when parent folder doesn't contain files

### ISSUE THREAD

**Issue by Vrihub** [smithdtyler/prettygoodmusicplayer#98] opened 2015-10-13 10:27 UTC
Consider this scenario:
Folder A doesn't contain music files, instead it contains folder B and folder C (which contain music files).
If I navigate to folder A, PGMP will display it as an empty folder, without displaying B and C. So music files in B and C are never reachable.

This bug doesn't happen when folder A is an immediate subfolder of the the root folder ("Music Directory" as configured in the settings), but if it's 2 or more levels down in the folder tree it will happen.

Tested on Version 3.2.15, on android 4.2.2

**Comment by smithdtyler** [comment] 2015-10-15 02:44
I need to think about this issue a bit. What you describe is, for the most part, the intended behavior of the app. That is, it expects that music is arranged by artist, then album, then songs. It doesn't expect a deeper level of nesting. 

This approach allows it to avoid the overhead of maintaining a database of known music files, while still presenting an organized view. The downside is it's not good at displaying content that isn't organized as expected.

**Comment by awquest** [comment] 2015-11-01 19:50
This surprised me, too. My folder structure varies a lot, e.g. some multi disc albums have each disc in a separate subfolder, also some podcasts etc.

Are the artist name and album title used for anything else except the "now playing" view? If not, maybe it could be approached like this: The user configures a root directory (which could even default to /sdcard), and when they play (root)/something/Artist/Album/1/Song.mp3, the "now playing" view shows all components below the root directory, i.e.

- something
- Artist
- Album
- 1
- Song

... scrolled to the bottom if it doesn't all fit on the screen. In other words, PGMP would have no opinion about the meaning of the folder structure, and thus be completely flexible.

Thank you by the way for your work. It is nice to finally have a good folder based open source player.

**Comment by Dreadeath** [comment] 2016-02-21 00:04
Any chances to see this fix? I mean why should structure be hardcoded in any way? It is very random for random people, just go down until you find music files, that's all this app need :)

**Comment by smithdtyler** [comment] 2016-02-21 12:42
I do plan to get a fix out, but this project is a bit lower than a few others in my queue, so I apologize for the slowness of my updates. There's a branch called [foldernames ](https://github.com/smithdtyler/prettygoodmusicplayer/tree/foldernames)where I've been doing some work on this task.

**Comment by smithdtyler** [comment] 2016-02-21 22:39
The playall branch has been updated with a fix to this issue. I'll merge the fix into master after a bit more testing. You're welcome to test it out too!

**Comment by smithdtyler** [comment] 2016-02-21 22:43
Beta release: https://drive.google.com/file/d/0BxNDTlnbuMgUNHN0R3NmWFdDQzQ/view?usp=sharing

**Comment by smithdtyler** [comment] 2016-02-23 04:17
This issue has been addressed in version 3.3.0. I've added a tag for this version, so it should be available on f-droid in 24-48 hours.

**Closed by smithdtyler** 2016-02-23 04:17 UTC

**Comment by Dreadeath** [comment] 2016-02-27 14:25
Hm, that's not what I expected. PGMP is now just pulling at some point all music files in one list, so if there are other "layers" such as albums, it becomes a mess of songs from all albums...

**Comment by smithdtyler** [comment] 2016-02-27 15:17
I'm open to making it more flexible. Any specific suggestions as to how to
handle arbitrary folderd epth?

**Comment by Dreadeath** [comment] 2016-02-29 01:45
Well...if app finds music files in folder it is in, then sort all these files by tracknumber and alphabetically? Otherwise act as file manager (sort of), just browse folders from the root. It is assumed that music is already sorted by folders, right? So there is no need to automate things more and go through all directories to find music. Also use of other color in titles would help if there are folder(-s) **and** music files in one folder.
